### ISSUE TITLE
YMChat is undefined

### ISSUE THREAD

**Issue by gauravsbagul** [yellowmessenger/ymchat-react-native#11]
I have initialized the chatbot setup, but can not open the bot. 
```
import { YMChat, YMChatEvents } from 'ymchat-react-native';

const ChatBot = () =>{


 useEffect(() => {
       _onInitialize()
    }, [])


    const _onInitialize = async () => {
         await YMChat?.setBotId("xXXXXX18382XXX");
        console.log('Log: ~> file: index.tsx ~> line 151 ~> _onInitialize ~> YMChat', YMChat)
    }

  const _onPrress = async () => {
        const res = await YMChat?.startChatbot()
     }

return (
<View>
    <Button onPrress={_onPrress}>
        <Text>
            Click me
        </Text>
   </Button>
</View>
)
}
```
We have uploaded this chatbot on the website also but it has a script and it is working fine there.

<img width="848" alt="Screenshot 2021-05-18 at 11 02 51 AM" src="https://user-images.githubusercontent.com/25247251/118595412-a7b60c00-b7c8-11eb-9203-dbb0c2136889.png">

**Comment by kaunteya** [comment]
@gauravsbagul we are looking into this. Will update you soon

**Comment by kaunteya** [comment]
@gauravsbagul by the time we look into this can you check the demo app that demonstrates how SDK can be integrated with the app?
Here is the link 
[https://github.com/yellowmessenger/ymchat-react-native-demo](https://github.com/yellowmessenger/ymchat-react-native-demo)

**Comment by gauravsbagul** [comment]
Ok.. Thanks.

**Comment by MadhanAD** [comment]
I'm facing the same issue. 
did you find any solution for this?
@kaunteya  @gauravsbagul

**Comment by kaunteya** [comment]
@MadhanAD can you share the steps to reproduce?

**Comment by MadhanAD** [comment]
This is my code,

`import { TouchableOpacity, View } from "react-native";

const YMChat = require("./node_modules/ymchat-react-native/index");

const App = () => {

  useEffect(() => {
    YMChat.YMChat.setBotId("My_YMCAHT_ID");
  }, []);

  return (
    <View>
      <TouchableOpacity onPress={() => {
        YMChat.YMChat.startChatBot();
      }}>
        Start Chat
      </TouchableOpacity>
    </View>
  );
};
`

**Comment by MadhanAD** [comment]
@kaunteya  any update?

**Comment by kaunteya** [comment]
@MadhanAD can you import YMChat the way it is suggested in the readme?
```
import YMChat from 'ymchat-react-native';
```

Please refer the demo app for integration reference https://github.com/yellowmessenger/ymchat-react-native-demo

**Comment by MadhanAD** [comment]
@kaunteya  My Project is in typescript, this library doesn't support typescript yet, 
so I have to call this library as I have shown.

**Comment by MadhanAD** [comment]
@kaunteya I have cloned the demo app from the repo use shared.

I'm facing the same issue on that demo app.
it says `Unresolved function or method startChatbot() `

None of the methods are accessible that shown in the demo project.

**Comment by MadhanAD** [comment]
@kaunteya  in addition to that, 
I'm getting the following error in the console 

 ```
ERROR  Invariant Violation: Native module cannot be null.
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[3], "ymchat-react-native").YMChat')
```

**Comment by kaunteya** [comment]
@MadhanAD can you share a demo project which reproduces the bug?

**Comment by MadhanAD** [comment]
@kaunteya  kindly find this demo project [https://github.com/MadhanAD/YmChatDemoTs](https://github.com/MadhanAD/YmChatDemoTs) 
you can find the issue that we are facing.

**Comment by kaunteya** [comment]
Thanks for sharing @MadhanAD. We will look into this
