### ISSUE TITLE
App crash on calling YMchat.closeBot();

### ISSUE THREAD

**Issue by harshaliitr** [yellowmessenger/ymchat-react-native#26]
Hello, 

My app is crashing when i call YMchat.closeBot(); 

Crash logs: 

java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'mqt_native_modules'.
All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {73b644d} called on Looper (mqt_native_modules, tid 9

package version: "ymchat-react-native": "^1.6.0"

**Comment by kaunteya** [comment]
We are looking into this issue. Will update you soon

**Comment by harshaliitr** [comment]
it's solved. you can close this issue. Thanks
