### ISSUE TITLE
How to accept bot params passed from react native?

### ISSUE THREAD

**Issue by harshaliitr** [yellowmessenger/ymchat-react-native#29]
I can see a solution in web client but it does not work for react native.

https://docs.yellow.ai/docs/platform_concepts/channelConfiguration/web/#share-user-data-from-parent-interface-to-bot-using-data-payload

Please help here @PurushYM @kaunteya

**Comment by PurushYM** [comment]
@blackhat @Arjun_Bhagat 

**For sending payload**
please follow documentation
link: https://docs.yellow.ai/docs/platform_concepts/channelConfiguration/react-native#payload

**For accessing payload** 
When payload is sent from mobile SDK it is always string JSON, please parse it before accessing the values

Here are steps to help you

* Add function node and add code to parse payload

    * Sample code
        ```javascript
        return new Promise(resolve => {
          let payload = data.profile.payload
          if (typeof (payload) == "string") {
            payload = JSON.parse(payload)
          }
          resolve(payload)
        });
      
     ![Function node](https://cdn.yellowmessenger.com/oBDNNuvBxaA31645604933497.png)


* Save the resolved value from function node to variable of type `Object` ( ex: `payload` )

   ![Code](https://cdn.yellowmessenger.com/UmBpcyxAv1l91645605023119.png)

* Now you can access the values on the variable ( ex: `{{{variables.payload.name}}}` )

  ![Variable access](https://cdn.yellowmessenger.com/jUgbEuASqAHf1645605063163.png)
